services:
  - type: web
    name: fintech-ltv-api
    env: python
    plan: free  # or 'starter' if you need more resources
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: H2O_JAVA_OPTIONS
        value: "-Xmx2g"
